FROM mysql:5.7
MAINTAINER ireland-interns@overstock.com

ENV MYSQL_ROOT_PASSWORD secret

#COPY ca.pem server-cert.pem server-key.pem /tmp/
#COPY run.sh /docker-entrypoint-initdb.d/
#RUN chown mysql:mysql /tmp/*.pem

